### ISSUE TITLE
add example/test for placing Lib and a Func in a struct

### ISSUE THREAD

**Issue by alexchandel** [tyleo/sharedlib#9]
I can't figure out the lifetimes. As far as I can tell, this should be valid:

```rust
use winapi::{HANDLE, DWORD, PCHAR, BOOL};

use winapi::{HMODULE, FARPROC};
use kernel32::{LoadLibraryA, FreeLibrary};
use sharedlib::{Lib, Func, Symbol, Result};

static path: &'static str = "winsta.dll\0";
type connect_a = extern "system" fn (hServer: HANDLE, SessionID: DWORD, TargetSessionID: DWORD, pPassword: *const u8, bWait: BOOL) -> BOOL;

pub struct Dll<'a> {
    lib: Lib,
    connect_a: Func<'a, connect_a>,
}
impl<'a> Dll<'a> {
    pub fn WinStationConnectA(&self, h: HANDLE, sid: DWORD, tsid: DWORD, pw: *const u8, wait: BOOL) -> BOOL {
        unsafe {
            self.connect_a.get()(h, sid, tsid, pw, wait)
        }
    }
}

pub fn load<'a>() -> Result<Dll<'a>> {
    let lib0: Lib = try!(unsafe {Lib::new(path)} );
    let sym = try!(unsafe {lib0.find_func("WinStationConnectA\0")});
    let dll: Dll<'a> = Dll {
        lib: lib0,
        connect_a: sym,
    };
    return Ok(dll)
}
```

It should be possible to put a Lib and a Func into a struct that's parameterized by a lifetime, since the Lib will outlive the Func. But the compiler claims that `lib0` only lives until the end of the function, even though I move it into `.lib`. Clearly I intend it to live as long as the `Dll` struct lives, but I see the problem that interior mutability in Dll could result in assignment to `.lib`.

I imagine this use case isn't unique, and I couldn't find any examples in the documentation showing the correct way to do this.

**Comment by tyleo** [comment]
Check out the new tests at the bottom of https://github.com/tyleo/sharedlib/blob/master/src/test/shared.rs

There are a few ways to do this. I provided examples for two safe ways, and one unsafe way.
